server:
  port: 8083
spring:
  kafka:
    template:
      default-topic: item-retry
    consumer:
      bootstrap-servers: localhost:9092
      group-id: retry-group-id
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: latest
  mail:
    host: smtp.gmail.com
    port: 587
    username: donotreplytestkafka12@gmail.com
    password: zdokvjxzrmdjeata #KafkaTestingEmail
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
email:
  details:
    to-address: abhinale8@gmail.com
    subject: The item is missing or low quantity in storage
    content: The item {item} is shortage in the storage. Please check the storage and add the item in storage or increase the quantity.
